notify:
  - slack:
      channels:
        - "moss#bk"
      message: "${BUILDKITE_BUILD_AUTHOR} ${BUILDKITE_REPO}"
    if: build.state == "blocked"

steps:
  - block: "Request Release"
    fields:
      - text: "Code Name"
        key: "release-name"

  - command: echo "doing the unblocked thing"
