steps:
  - name: ":hammer: Example Script"
    command: "./script.sh"
    artifact_paths: "artifacts/*"
    plugins:
      docker#v3.7.0:
        image: ubuntu
        run: bash
        mount-buildkite-agent: true
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
