steps:
  - command: echo "do it"
    label: "tests"

  - wait

  - block: ":shipit: Deploy Frontend?"
    branches: "master"
  - build:
      env:
        BUILDKITE_PULL_REQUEST: "false"
        BUILDKITE_PULL_REQUEST_REPO: ""
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: ""
      message: "Merge pull request #137 from envato/691-custom-elements-products-gallery-block\n\nImplement Elements Image Gallery Block in Gutenberg"
    label: ":rocket: Deploy Frontend"
    trigger: "trigger-me"
