steps:
  - label: "do stuff"
    command: .buildkite/test.sh
    key: "step-one"

  - label: ":console: Annotation Deployment"
    depends_on: "step-two"
    command: |
      buildkite-agent annotate 'Example `default` style' --context 'ctx-default'
