steps:
  - command: |
      bamboo_buildKey=$BUILDKITE_PIPELINE_SLUG-$BUILDKITE_BUILD_NUMBER
      bamboo_buildResultKey=$BUILDKITE_PIPELINE_SLUG-$BUILDKITE_BUILD_NUMBER
      bamboo_buildResultsUrl=$BUILDKITE_BUILD_URL

      echo $bamboo_buildKey
      echo $bamboo_buildResultKey
      echo $bamboo_buildResultsUrl
