steps:
  - name: ":hammer: Example Script"
    command: "./script.sh"
    artifact_paths: "artifacts/*"
    plugins:
      /Users/jj/bk/plugins/docker-buildkite-plugin:
        image: "bash"
        run: bash
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
