#!/bin/bash

set -eu

VALUE=buildkite-agent step get "outcome" --step "step1"

echo "$VALUE"
 
if [[ "$BUILDKITE_STEP_KEY" == "first" ]]; then
    .buildkite/pipeline.sh | buildkite-agent pipeline upload
fi